### ISSUE TITLE
Help with sketch

### ISSUE THREAD

**Issue by jpgagnon73** [mattrcampbell/EOSEncoderWing#2]
Matt, i'm now getting to play with this project.  A couple questions.  I am using ARDUINO to load the sketch. I cannot install the modified adafruit library.  It says "Specified folder/zip file does not contain a valid library"  any ideas why?

What are the pin outs?  I see the switches but not sure where the OLED displays plug into and the encoder wheels do.

I think i've designed a really cool enclosure to hold it all that slides over the Cherry SPOS keyboard.  Very excited.

Thanks for you help and work on this project.

JP

**Comment by mattrcampbell** [comment]
Hmm, that is strange, the ZIP file appears to be empty!  I am at work at the moment and I don't have the code here, I will need to look at that later. If you are only using 2 OLED displays however you can get along fine with the standard Adafruit OLED library.

As for the pins, the OLED displays are i2c so the pins depend on what microcontroller you are using.  I did not use an Arduino, but rather used a Teensy.  An Uno did not have enough storage AND I needed something with 2 i2c ports.  
On the Teensy I used pins 25-32 for the encoders.

I have seen your pics on Facebook, looks neat!  It also looks like you are not using OLED so you will need to change up any of the code that talks to the displays to handle your LCD. 

Good luck!

**Comment by jpgagnon73** [comment]
I'm using a Teensy 3.2 board and 4 OLED displays.  The unit I've been showing on Facebook is the light hack project from ETC. I've designed it now with 4 encoders, 4 displays and 6 buttons above the displays.  it's starting to look like stadium seating on my Cherry keyboard! LOL.  Any help would be greatly appreciated when you have time to check it out.  Never used Teensy before.

**Comment by jpgagnon73** [comment]
Hey Matt, any luck with figuring out what's wrong with the code?  I am going to printout my enclosure over the holiday weekend and was hoping to assemble it too.  Thanks for your help.

**Comment by mattrcampbell** [comment]
I have updated the zip file and filled in the missing content.
